# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import instserver_pb2 as instserver__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in instserver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InstrumentServerStub(object):
    """═══════════════════════════════════════════
    Control Plane — 強型別 protobuf
    ═══════════════════════════════════════════

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AssignExperiment = channel.unary_unary(
                '/instserver.InstrumentServer/AssignExperiment',
                request_serializer=instserver__pb2.AssignReq.SerializeToString,
                response_deserializer=instserver__pb2.StatusResp.FromString,
                _registered_method=True)
        self.SetInputs = channel.unary_unary(
                '/instserver.InstrumentServer/SetInputs',
                request_serializer=instserver__pb2.SetInputsReq.SerializeToString,
                response_deserializer=instserver__pb2.StatusResp.FromString,
                _registered_method=True)
        self.ConnectAll = channel.unary_unary(
                '/instserver.InstrumentServer/ConnectAll',
                request_serializer=instserver__pb2.SessionReq.SerializeToString,
                response_deserializer=instserver__pb2.StatusResp.FromString,
                _registered_method=True)
        self.RunExperiment = channel.unary_unary(
                '/instserver.InstrumentServer/RunExperiment',
                request_serializer=instserver__pb2.SessionReq.SerializeToString,
                response_deserializer=instserver__pb2.StatusResp.FromString,
                _registered_method=True)
        self.StopExperiment = channel.unary_unary(
                '/instserver.InstrumentServer/StopExperiment',
                request_serializer=instserver__pb2.SessionReq.SerializeToString,
                response_deserializer=instserver__pb2.StatusResp.FromString,
                _registered_method=True)
        self.AbortExperiment = channel.unary_unary(
                '/instserver.InstrumentServer/AbortExperiment',
                request_serializer=instserver__pb2.SessionReq.SerializeToString,
                response_deserializer=instserver__pb2.StatusResp.FromString,
                _registered_method=True)
        self.DisconnectAll = channel.unary_unary(
                '/instserver.InstrumentServer/DisconnectAll',
                request_serializer=instserver__pb2.SessionReq.SerializeToString,
                response_deserializer=instserver__pb2.StatusResp.FromString,
                _registered_method=True)
        self.CleanExperiment = channel.unary_unary(
                '/instserver.InstrumentServer/CleanExperiment',
                request_serializer=instserver__pb2.SessionReq.SerializeToString,
                response_deserializer=instserver__pb2.StatusResp.FromString,
                _registered_method=True)
        self.GetInputSchema = channel.unary_unary(
                '/instserver.InstrumentServer/GetInputSchema',
                request_serializer=instserver__pb2.SchemaReq.SerializeToString,
                response_deserializer=instserver__pb2.SchemaResp.FromString,
                _registered_method=True)
        self.GetExperimentList = channel.unary_unary(
                '/instserver.InstrumentServer/GetExperimentList',
                request_serializer=instserver__pb2.Empty.SerializeToString,
                response_deserializer=instserver__pb2.ExpListResp.FromString,
                _registered_method=True)
        self.ReadFile = channel.unary_unary(
                '/instserver.InstrumentServer/ReadFile',
                request_serializer=instserver__pb2.FileReq.SerializeToString,
                response_deserializer=instserver__pb2.FileResp.FromString,
                _registered_method=True)
        self.SaveFile = channel.unary_unary(
                '/instserver.InstrumentServer/SaveFile',
                request_serializer=instserver__pb2.SaveFileReq.SerializeToString,
                response_deserializer=instserver__pb2.StatusResp.FromString,
                _registered_method=True)
        self.CheckFileTime = channel.unary_unary(
                '/instserver.InstrumentServer/CheckFileTime',
                request_serializer=instserver__pb2.FileTimeReq.SerializeToString,
                response_deserializer=instserver__pb2.FileTimeResp.FromString,
                _registered_method=True)
        self.CreateFolder = channel.unary_unary(
                '/instserver.InstrumentServer/CreateFolder',
                request_serializer=instserver__pb2.FolderReq.SerializeToString,
                response_deserializer=instserver__pb2.StatusResp.FromString,
                _registered_method=True)
        self.CopyFolder = channel.unary_unary(
                '/instserver.InstrumentServer/CopyFolder',
                request_serializer=instserver__pb2.CopyFolderReq.SerializeToString,
                response_deserializer=instserver__pb2.StatusResp.FromString,
                _registered_method=True)
        self.ListTools = channel.unary_unary(
                '/instserver.InstrumentServer/ListTools',
                request_serializer=instserver__pb2.Empty.SerializeToString,
                response_deserializer=instserver__pb2.FileListResp.FromString,
                _registered_method=True)
        self.ListTemplates = channel.unary_unary(
                '/instserver.InstrumentServer/ListTemplates',
                request_serializer=instserver__pb2.Empty.SerializeToString,
                response_deserializer=instserver__pb2.FileListResp.FromString,
                _registered_method=True)
        self.StartMonitor = channel.unary_unary(
                '/instserver.InstrumentServer/StartMonitor',
                request_serializer=instserver__pb2.StartMonitorReq.SerializeToString,
                response_deserializer=instserver__pb2.StatusResp.FromString,
                _registered_method=True)
        self.StopMonitor = channel.unary_unary(
                '/instserver.InstrumentServer/StopMonitor',
                request_serializer=instserver__pb2.SessionReq.SerializeToString,
                response_deserializer=instserver__pb2.StatusResp.FromString,
                _registered_method=True)
        self.GetMonitorSchema = channel.unary_unary(
                '/instserver.InstrumentServer/GetMonitorSchema',
                request_serializer=instserver__pb2.SchemaReq.SerializeToString,
                response_deserializer=instserver__pb2.SchemaResp.FromString,
                _registered_method=True)
        self.ListMonitors = channel.unary_unary(
                '/instserver.InstrumentServer/ListMonitors',
                request_serializer=instserver__pb2.Empty.SerializeToString,
                response_deserializer=instserver__pb2.ExpListResp.FromString,
                _registered_method=True)
        self.StreamUpdates = channel.unary_stream(
                '/instserver.InstrumentServer/StreamUpdates',
                request_serializer=instserver__pb2.StreamReq.SerializeToString,
                response_deserializer=instserver__pb2.DataFrame.FromString,
                _registered_method=True)
        self.RunCode = channel.unary_stream(
                '/instserver.InstrumentServer/RunCode',
                request_serializer=instserver__pb2.CodeReq.SerializeToString,
                response_deserializer=instserver__pb2.CodeFrame.FromString,
                _registered_method=True)
        self.StopCode = channel.unary_unary(
                '/instserver.InstrumentServer/StopCode',
                request_serializer=instserver__pb2.SessionReq.SerializeToString,
                response_deserializer=instserver__pb2.StatusResp.FromString,
                _registered_method=True)
        self.StreamMonitor = channel.unary_stream(
                '/instserver.InstrumentServer/StreamMonitor',
                request_serializer=instserver__pb2.StreamReq.SerializeToString,
                response_deserializer=instserver__pb2.DataFrame.FromString,
                _registered_method=True)


class InstrumentServerServicer(object):
    """═══════════════════════════════════════════
    Control Plane — 強型別 protobuf
    ═══════════════════════════════════════════

    """

    def AssignExperiment(self, request, context):
        """實驗生命週期
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetInputs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunExperiment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopExperiment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortExperiment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisconnectAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanExperiment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInputSchema(self, request, context):
        """Schema 查詢
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExperimentList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """檔案操作
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckFileTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFolder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CopyFolder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTools(self, request, context):
        """檔案列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTemplates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartMonitor(self, request, context):
        """Monitor 控制（24/7 儀器讀值；獨立 lane，不佔 experiment session slot）
        回傳 session_id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopMonitor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMonitorSchema(self, request, context):
        """只填 output_schema
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMonitors(self, request, context):
        """列 monitors/ 目錄
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamUpdates(self, request, context):
        """═══════════════════════════════════════════
        Data Plane — stream + msgpack payload
        ═══════════════════════════════════════════

        即時實驗數據 streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunCode(self, request, context):
        """互動式程式碼 streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMonitor(self, request, context):
        """Monitor 讀值 streaming（復用 DataFrame 封包 + build_patches）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InstrumentServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AssignExperiment': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignExperiment,
                    request_deserializer=instserver__pb2.AssignReq.FromString,
                    response_serializer=instserver__pb2.StatusResp.SerializeToString,
            ),
            'SetInputs': grpc.unary_unary_rpc_method_handler(
                    servicer.SetInputs,
                    request_deserializer=instserver__pb2.SetInputsReq.FromString,
                    response_serializer=instserver__pb2.StatusResp.SerializeToString,
            ),
            'ConnectAll': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectAll,
                    request_deserializer=instserver__pb2.SessionReq.FromString,
                    response_serializer=instserver__pb2.StatusResp.SerializeToString,
            ),
            'RunExperiment': grpc.unary_unary_rpc_method_handler(
                    servicer.RunExperiment,
                    request_deserializer=instserver__pb2.SessionReq.FromString,
                    response_serializer=instserver__pb2.StatusResp.SerializeToString,
            ),
            'StopExperiment': grpc.unary_unary_rpc_method_handler(
                    servicer.StopExperiment,
                    request_deserializer=instserver__pb2.SessionReq.FromString,
                    response_serializer=instserver__pb2.StatusResp.SerializeToString,
            ),
            'AbortExperiment': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortExperiment,
                    request_deserializer=instserver__pb2.SessionReq.FromString,
                    response_serializer=instserver__pb2.StatusResp.SerializeToString,
            ),
            'DisconnectAll': grpc.unary_unary_rpc_method_handler(
                    servicer.DisconnectAll,
                    request_deserializer=instserver__pb2.SessionReq.FromString,
                    response_serializer=instserver__pb2.StatusResp.SerializeToString,
            ),
            'CleanExperiment': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanExperiment,
                    request_deserializer=instserver__pb2.SessionReq.FromString,
                    response_serializer=instserver__pb2.StatusResp.SerializeToString,
            ),
            'GetInputSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInputSchema,
                    request_deserializer=instserver__pb2.SchemaReq.FromString,
                    response_serializer=instserver__pb2.SchemaResp.SerializeToString,
            ),
            'GetExperimentList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExperimentList,
                    request_deserializer=instserver__pb2.Empty.FromString,
                    response_serializer=instserver__pb2.ExpListResp.SerializeToString,
            ),
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=instserver__pb2.FileReq.FromString,
                    response_serializer=instserver__pb2.FileResp.SerializeToString,
            ),
            'SaveFile': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveFile,
                    request_deserializer=instserver__pb2.SaveFileReq.FromString,
                    response_serializer=instserver__pb2.StatusResp.SerializeToString,
            ),
            'CheckFileTime': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckFileTime,
                    request_deserializer=instserver__pb2.FileTimeReq.FromString,
                    response_serializer=instserver__pb2.FileTimeResp.SerializeToString,
            ),
            'CreateFolder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFolder,
                    request_deserializer=instserver__pb2.FolderReq.FromString,
                    response_serializer=instserver__pb2.StatusResp.SerializeToString,
            ),
            'CopyFolder': grpc.unary_unary_rpc_method_handler(
                    servicer.CopyFolder,
                    request_deserializer=instserver__pb2.CopyFolderReq.FromString,
                    response_serializer=instserver__pb2.StatusResp.SerializeToString,
            ),
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=instserver__pb2.Empty.FromString,
                    response_serializer=instserver__pb2.FileListResp.SerializeToString,
            ),
            'ListTemplates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTemplates,
                    request_deserializer=instserver__pb2.Empty.FromString,
                    response_serializer=instserver__pb2.FileListResp.SerializeToString,
            ),
            'StartMonitor': grpc.unary_unary_rpc_method_handler(
                    servicer.StartMonitor,
                    request_deserializer=instserver__pb2.StartMonitorReq.FromString,
                    response_serializer=instserver__pb2.StatusResp.SerializeToString,
            ),
            'StopMonitor': grpc.unary_unary_rpc_method_handler(
                    servicer.StopMonitor,
                    request_deserializer=instserver__pb2.SessionReq.FromString,
                    response_serializer=instserver__pb2.StatusResp.SerializeToString,
            ),
            'GetMonitorSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMonitorSchema,
                    request_deserializer=instserver__pb2.SchemaReq.FromString,
                    response_serializer=instserver__pb2.SchemaResp.SerializeToString,
            ),
            'ListMonitors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMonitors,
                    request_deserializer=instserver__pb2.Empty.FromString,
                    response_serializer=instserver__pb2.ExpListResp.SerializeToString,
            ),
            'StreamUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamUpdates,
                    request_deserializer=instserver__pb2.StreamReq.FromString,
                    response_serializer=instserver__pb2.DataFrame.SerializeToString,
            ),
            'RunCode': grpc.unary_stream_rpc_method_handler(
                    servicer.RunCode,
                    request_deserializer=instserver__pb2.CodeReq.FromString,
                    response_serializer=instserver__pb2.CodeFrame.SerializeToString,
            ),
            'StopCode': grpc.unary_unary_rpc_method_handler(
                    servicer.StopCode,
                    request_deserializer=instserver__pb2.SessionReq.FromString,
                    response_serializer=instserver__pb2.StatusResp.SerializeToString,
            ),
            'StreamMonitor': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMonitor,
                    request_deserializer=instserver__pb2.StreamReq.FromString,
                    response_serializer=instserver__pb2.DataFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'instserver.InstrumentServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('instserver.InstrumentServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InstrumentServer(object):
    """═══════════════════════════════════════════
    Control Plane — 強型別 protobuf
    ═══════════════════════════════════════════

    """

    @staticmethod
    def AssignExperiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instserver.InstrumentServer/AssignExperiment',
            instserver__pb2.AssignReq.SerializeToString,
            instserver__pb2.StatusResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetInputs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instserver.InstrumentServer/SetInputs',
            instserver__pb2.SetInputsReq.SerializeToString,
            instserver__pb2.StatusResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConnectAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instserver.InstrumentServer/ConnectAll',
            instserver__pb2.SessionReq.SerializeToString,
            instserver__pb2.StatusResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunExperiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instserver.InstrumentServer/RunExperiment',
            instserver__pb2.SessionReq.SerializeToString,
            instserver__pb2.StatusResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopExperiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instserver.InstrumentServer/StopExperiment',
            instserver__pb2.SessionReq.SerializeToString,
            instserver__pb2.StatusResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortExperiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instserver.InstrumentServer/AbortExperiment',
            instserver__pb2.SessionReq.SerializeToString,
            instserver__pb2.StatusResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisconnectAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instserver.InstrumentServer/DisconnectAll',
            instserver__pb2.SessionReq.SerializeToString,
            instserver__pb2.StatusResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CleanExperiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instserver.InstrumentServer/CleanExperiment',
            instserver__pb2.SessionReq.SerializeToString,
            instserver__pb2.StatusResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInputSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instserver.InstrumentServer/GetInputSchema',
            instserver__pb2.SchemaReq.SerializeToString,
            instserver__pb2.SchemaResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExperimentList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instserver.InstrumentServer/GetExperimentList',
            instserver__pb2.Empty.SerializeToString,
            instserver__pb2.ExpListResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instserver.InstrumentServer/ReadFile',
            instserver__pb2.FileReq.SerializeToString,
            instserver__pb2.FileResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instserver.InstrumentServer/SaveFile',
            instserver__pb2.SaveFileReq.SerializeToString,
            instserver__pb2.StatusResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckFileTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instserver.InstrumentServer/CheckFileTime',
            instserver__pb2.FileTimeReq.SerializeToString,
            instserver__pb2.FileTimeResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateFolder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instserver.InstrumentServer/CreateFolder',
            instserver__pb2.FolderReq.SerializeToString,
            instserver__pb2.StatusResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CopyFolder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instserver.InstrumentServer/CopyFolder',
            instserver__pb2.CopyFolderReq.SerializeToString,
            instserver__pb2.StatusResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instserver.InstrumentServer/ListTools',
            instserver__pb2.Empty.SerializeToString,
            instserver__pb2.FileListResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTemplates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instserver.InstrumentServer/ListTemplates',
            instserver__pb2.Empty.SerializeToString,
            instserver__pb2.FileListResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartMonitor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instserver.InstrumentServer/StartMonitor',
            instserver__pb2.StartMonitorReq.SerializeToString,
            instserver__pb2.StatusResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopMonitor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instserver.InstrumentServer/StopMonitor',
            instserver__pb2.SessionReq.SerializeToString,
            instserver__pb2.StatusResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMonitorSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instserver.InstrumentServer/GetMonitorSchema',
            instserver__pb2.SchemaReq.SerializeToString,
            instserver__pb2.SchemaResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMonitors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instserver.InstrumentServer/ListMonitors',
            instserver__pb2.Empty.SerializeToString,
            instserver__pb2.ExpListResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/instserver.InstrumentServer/StreamUpdates',
            instserver__pb2.StreamReq.SerializeToString,
            instserver__pb2.DataFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/instserver.InstrumentServer/RunCode',
            instserver__pb2.CodeReq.SerializeToString,
            instserver__pb2.CodeFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instserver.InstrumentServer/StopCode',
            instserver__pb2.SessionReq.SerializeToString,
            instserver__pb2.StatusResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMonitor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/instserver.InstrumentServer/StreamMonitor',
            instserver__pb2.StreamReq.SerializeToString,
            instserver__pb2.DataFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
